#!/bin/sh
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo
./clean


gmcs /target:library Accountant.cs AssemblyInfo-Base.cs Byter.cs Core.cs DataSet.cs Entity.cs FastPanel.cs Fractals.cs IAbstractor.cs Interaction.cs Keyboard.cs Mass3D.cs MyCallback.cs Packet.cs Packeter.cs Port.cs PseudoRandom.cs RAnim_bgra32.cs RConvert.cs RForm.cs RForms.cs RFont_bgra32.cs RGradient_bgra32.cs RImage_bgra32.cs RMath.cs RMemory.cs RPlatform.cs RPlatform.Sdl.cs RReporting.cs RTextBox.cs RTypes.cs Scene3D.cs Sprite.cs StringQ.cs StringStack.cs Table.cs Test.cs Var.cs Variables.cs WaveStream.cs -unsafe /reference:System.Windows.Forms.dll /reference:System.Drawing.dll /reference:System.Runtime.Remoting.dll /reference:../bin/Tao.Sdl.dll 2> err.txt
killall outputinspector
outputinspector&
sleep 1
#only needs to reference Tao.Sdl.dll when using PlatformNow_Sdl.cs
#Base.dll use to contain the old RetroEngine.cs, and the executable contained a file called RetroEngineWindow.cs
gmcs RetroEngine.cs AssemblyInfo-RetroEngine.cs -unsafe /reference:System.Windows.Forms.dll /reference:System.Drawing.dll /reference:Base.dll /reference:../bin/Tao.Sdl.dll /reference:System.Web.dll 2> err.txt
outputinspector&
#mcs Server.cs AssemblyInfo-Server.cs /reference:System.Drawing.dll /reference:System.Runtime.Remoting.dll /reference:Base.dll
#NOW THE SERVER is something more abstract, and is created by RetroEngine.exe
mv -f ../bin/Base.dll ../bin/Base.dll.wip
mv Base.dll ../bin
#mv Server.exe ../bin
mv -f ../bin/RetroEngine.exe ../bin/RetroEngine.exe.wip
mv RetroEngine.exe ../bin

#deprecated:
#build
#mcs /target:library ExpertMultimedia.Script.cs
#mcs /target:library ExpertMultimedia.DataTypes.cs Buffer.cs -unsafe /reference:System.Drawing.dll
#mcs /target:library ExpertMultimedia.Port.cs ExpertMultimedia.Packet.cs ExpertMultimedia.Core.cs /reference:ExpertMultimedia.Script.dll
#mcs ServerStart.cs /reference:ExpertMultimedia.Port.dll /reference:ExpertMultimedia.Script.dll /reference:System.Runtime.Remoting.dll
#mcs /target:library ExpertMultimedia.Client.cs /reference:ExpertMultimedia.Port.dll /reference:ExpertMultimedia.Script.dll /reference:System.Runtime.Remoting.dll
#mcs RetroEngine.cs /reference:System.Windows.Forms.dll /reference:System.Drawing.dll /reference:ExpertMultimedia.Script.dll /reference:ExpertMultimedia.DataTypes.dll /reference:ExpertMultimedia.Client.dll /reference:System.Data.dll
#move binaries
#mv ExpertMultimedia.Script.dll bin
#mv ExpertMultimedia.Port.dll bin
#mv ExpertMultimedia.Client.dll bin
#mv ExpertMultimedia.DataTypes.dll bin
